apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
  labels: 
    app: spring-boot
spec:
  selector:
    matchLabels:
      app: spring-boot
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: users-mysql
        image: users-mysql
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  labels:
    app: spring-boot
spec:
  ports:
    - port: 8086
  selector:
    app: spring-boot
  type: LoadBalancer
